# 이벤트 타입 상수
# 이 파일은 websocket-schema 프로젝트의 tools/generate_message_type_constants.py 에 의해 생성됩니다.
class MESSAGE_TYPE:
    APPLY_DISCOUNT = "apply_discount"
    CANCEL_PAYMENT = "cancel_payment"
    CHANGE_VAD_SETTINGS = "change_vad_settings"
    CHANGE_ENVIRONMENT = "change_environment"
    COMPLETE_PAYMENT = "complete_payment"
    PAGE_TRANSITION = "page_transition"
    PAYMENT_ERROR = "payment_error"
    PAYMENT_RESULT = "payment_result"
    PERSON_ENTERED = "person_entered"
    PERSON_LEFT = "person_left"
    PING = "ping"
    RESET_ORDER = "reset_order"
    SET_AVATAR_INTERRUPT_MODE_WHEN_HUMAN_VOICE = "set_avatar_interrupt_mode_when_human_voice"
    SET_AVATAR_INTERRUPT_MODE = "set_avatar_interrupt_mode"
    SET_ONBOARDING_ENABLED = "set_onboarding_enabled"
    START_ORDER = "start_order"
    START_PAYMENT = "start_payment"
    UPDATE_CART = "update_cart"
    SPEECH_START = "speech_start"
    SPEECH_STOP = "speech_stop"
    OPEN_MIC = "open_mic"
    CLOSE_MIC = "close_mic"
    SPEECH_RESULT = "speech_result"
    VAD_ERROR = "vad_error"
    VAD_TIMEOUT = "vad_timeout"
    SPEECH_PITCH = "speech_pitch"
